{{- if and .Values.ingress.enabled .Values.ingress.basicAuth.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: registry-auth
  labels:
    app.kubernetes.io/name: registry-auth
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  basicAuth:
    secret: {{ .Values.ingress.basicAuth.secretName }}
    removeHeader: true
{{- end }}
