apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.registry.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.registry.storage.size }}
