apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: registry
  ports:
    - name: registry
      port: {{ .Values.registry.service.port }}
      targetPort: registry
      protocol: TCP
