{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
  labels:
    app.kubernetes.io/name: registry-ui
    app.kubernetes.io/part-of: {{ .Chart.Name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: registry-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: registry-ui
    spec:
      containers:
        - name: registry-ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          env:
            - name: REGISTRY_TITLE
              value: {{ .Values.ui.title | quote }}
            - name: SINGLE_REGISTRY
              value: "true"
            - name: DELETE_IMAGES
              value: {{ .Values.ui.deleteImages | quote }}
            - name: SHOW_CONTENT_DIGEST
              value: {{ .Values.ui.showDigest | quote }}
            - name: CATALOG_ELEMENTS_LIMIT
              value: "100"
            - name: NGINX_PROXY_PASS_URL
              value: "http://registry:{{ .Values.registry.service.port }}"
          ports:
            - name: http
              containerPort: {{ .Values.ui.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
{{- end }}
