apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: container-registry
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bikstok/fitlogger-infra.git
    targetRevision: HEAD
    path: charts/container-registry
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: container-registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
